Dynamic blog link
GlobalDigitalLibraryio/gdl-home pull request #2
Opened 2019-07-23 07:38 UTC by camilve

2019-07-24 11:26 UTC, vikre commented on src/components/header.js
> +    let blogPath = "https://blog.digitallibrary.io/"
Tanken er at man skal kunne nå `(test|staging|demo).blog.digitallibrary.io` når man er i `test|staging|demo` også. Med denne så når man alltid produksjon uansett hvilket miljø man er i :)

For å vite hvilket miljø man kjører i, så bruker vi noe som heter environment variabler. Så hvis du prøver å kjøre opp appen med `GATSBY_GDL_ENVIRONMENT=test` så skal du i appen kunne si `process.env.GATSBY_GDL_ENVIRONMENT` for å få ut "test", og dermed kunne sette riktig url.

2019-07-24 11:26 UTC, vikre requested changes
Se kommentaren i koden :)

2019-07-29 06:53 UTC, vikre requested changes
Noen småting - også i feks `Cover.js` hvor du typer `children` så må du importere alt fra `react` samt endre typen for children til `React.Node` ( `children: React.Node`)

2019-07-29 06:53 UTC, vikre commented on src/components/backButton.js
> +        style={{ marginTop: 20, display: "inline-flex" }}
Du kan sikkert skrive om denne komponenten til å ikke bruke klasse :)
```
const BackButton = () => (
  <ButtonBase
    focusRipple
    style={{ marginTop: 20, display: "inline-flex" }}
    onClick={() => window.history.back()}
  >
    <ArrowBack style={{ fontSize: 30, color: "#3c5a99" }} />
    <Typography
      style={{
        marginLeft: 5,
        fontWeight: "bold",
        color: "#3c5a99",
        fontSize: "10pt",
      }}
    >
      BACK
    </Typography>
  </ButtonBase>
)

export default BackButton
```

2019-07-29 06:53 UTC, vikre commented on src/pages/gdl-in-the-news.js
> +        <div className="news-grid">
For at `flow` skal bli riktig må du si `import * as React from "react"` for da importerer du alt fra react, og kan aksessere det igjennom `React.<something>`. (Det må du gjøre alle steder :) )

Også blir vel ikke props-typingen din helt riktig her?

2019-07-29 06:53 UTC, vikre commented on src/pages/index.js
> +        blogPath = `https://${env}.blog.digitallibrary.io/`
Bra du lagde pr, for jeg ser at jeg også har byttet på her, skal være: `https://blog.${env}.digitallibrary.io/`

2019-07-29 07:10 UTC, vikre commented on src/pages/gdl-in-the-news.js
> +        <div className="news-grid">
Du kan jo feks se hvordan Frida har gjort det i `allPosts.js` i `gdl-blog`

2019-10-14 09:45 UTC, kievu approved these changes

2019-10-14 09:45 UTC, merged